# Generated by Django 4.2 on 2024-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Best Movie', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watch',
            field=models.URLField(default='dashboard.render.com'),
            preserve_default=False,
        ),
    ]
