name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python manage.py test

      - name: Run API Tests
        run: python manage.py test api

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run e2e Tests
        run: pytest --tracing=retain-on-failure

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: test-results/
          